### ISSUE TITLE
Authentication System

### ISSUE THREAD

**Issue by YasinYA** [YasinYA/MyBlog2#1]
when the admin user logs in he will be redirect to the `/dashbaord`  page . the issues isn't the loging in it self, but it is when  unauthorized user tries to navigate to the `/dashboard` he must be redirected  to the `/ home` page instead he can go to `/dashboard`, so how can i prevent that?

@aaronmyatt

**Comment by aaronmyatt** [comment]
@YasinYA: In Angular routing you can assign a callback check that must be satisfied before the user is able to reach a particular view.

Look for 'resolve': https://docs.angularjs.org/api/ngRoute/provider/$routeProvider

Although this example uses Ionic, it describes the authentication problem well: https://devdactic.com/user-auth-angularjs-ionic/

**Comment by YasinYA** [comment]
this is closed by this pull request #2
